// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/echo/echo.proto

package echo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoService_UnaryEcho_FullMethodName                  = "/echo.EchoService/UnaryEcho"
	EchoService_BidirectionalStreamingEcho_FullMethodName = "/echo.EchoService/BidirectionalStreamingEcho"
)

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoServiceClient interface {
	UnaryEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	BidirectionalStreamingEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error)
}

type echoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoServiceClient(cc grpc.ClientConnInterface) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) UnaryEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, EchoService_UnaryEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) BidirectionalStreamingEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EchoService_ServiceDesc.Streams[0], EchoService_BidirectionalStreamingEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EchoService_BidirectionalStreamingEchoClient = grpc.BidiStreamingClient[EchoRequest, EchoResponse]

// EchoServiceServer is the server API for EchoService service.
// All implementations must embed UnimplementedEchoServiceServer
// for forward compatibility.
type EchoServiceServer interface {
	UnaryEcho(context.Context, *EchoRequest) (*EchoResponse, error)
	BidirectionalStreamingEcho(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error
	mustEmbedUnimplementedEchoServiceServer()
}

// UnimplementedEchoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServiceServer struct{}

func (UnimplementedEchoServiceServer) UnaryEcho(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryEcho not implemented")
}
func (UnimplementedEchoServiceServer) BidirectionalStreamingEcho(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamingEcho not implemented")
}
func (UnimplementedEchoServiceServer) mustEmbedUnimplementedEchoServiceServer() {}
func (UnimplementedEchoServiceServer) testEmbeddedByValue()                     {}

// UnsafeEchoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServiceServer will
// result in compilation errors.
type UnsafeEchoServiceServer interface {
	mustEmbedUnimplementedEchoServiceServer()
}

func RegisterEchoServiceServer(s grpc.ServiceRegistrar, srv EchoServiceServer) {
	// If the following call pancis, it indicates UnimplementedEchoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoService_ServiceDesc, srv)
}

func _EchoService_UnaryEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).UnaryEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoService_UnaryEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).UnaryEcho(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_BidirectionalStreamingEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServiceServer).BidirectionalStreamingEcho(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EchoService_BidirectionalStreamingEchoServer = grpc.BidiStreamingServer[EchoRequest, EchoResponse]

// EchoService_ServiceDesc is the grpc.ServiceDesc for EchoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryEcho",
			Handler:    _EchoService_UnaryEcho_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalStreamingEcho",
			Handler:       _EchoService_BidirectionalStreamingEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/echo/echo.proto",
}

const (
	SecureService_SecureEcho_FullMethodName        = "/echo.SecureService/SecureEcho"
	SecureService_SecureBidiEcho_FullMethodName    = "/echo.SecureService/SecureBidiEcho"
	SecureService_UnorderedBidiEcho_FullMethodName = "/echo.SecureService/UnorderedBidiEcho"
	SecureService_InspectOuter_FullMethodName      = "/echo.SecureService/InspectOuter"
)

// SecureServiceClient is the client API for SecureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecureService uses the SecureEnvelope
type SecureServiceClient interface {
	SecureEcho(ctx context.Context, in *SecureEnvelope, opts ...grpc.CallOption) (*SecureEnvelope, error)
	SecureBidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope], error)
	UnorderedBidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope], error)
	InspectOuter(ctx context.Context, in *SecureEnvelope, opts ...grpc.CallOption) (*SecureEnvelope, error)
}

type secureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureServiceClient(cc grpc.ClientConnInterface) SecureServiceClient {
	return &secureServiceClient{cc}
}

func (c *secureServiceClient) SecureEcho(ctx context.Context, in *SecureEnvelope, opts ...grpc.CallOption) (*SecureEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecureEnvelope)
	err := c.cc.Invoke(ctx, SecureService_SecureEcho_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureServiceClient) SecureBidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecureService_ServiceDesc.Streams[0], SecureService_SecureBidiEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecureEnvelope, SecureEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecureService_SecureBidiEchoClient = grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope]

func (c *secureServiceClient) UnorderedBidiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecureService_ServiceDesc.Streams[1], SecureService_UnorderedBidiEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecureEnvelope, SecureEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecureService_UnorderedBidiEchoClient = grpc.BidiStreamingClient[SecureEnvelope, SecureEnvelope]

func (c *secureServiceClient) InspectOuter(ctx context.Context, in *SecureEnvelope, opts ...grpc.CallOption) (*SecureEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecureEnvelope)
	err := c.cc.Invoke(ctx, SecureService_InspectOuter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecureServiceServer is the server API for SecureService service.
// All implementations must embed UnimplementedSecureServiceServer
// for forward compatibility.
//
// SecureService uses the SecureEnvelope
type SecureServiceServer interface {
	SecureEcho(context.Context, *SecureEnvelope) (*SecureEnvelope, error)
	SecureBidiEcho(grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]) error
	UnorderedBidiEcho(grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]) error
	InspectOuter(context.Context, *SecureEnvelope) (*SecureEnvelope, error)
	mustEmbedUnimplementedSecureServiceServer()
}

// UnimplementedSecureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecureServiceServer struct{}

func (UnimplementedSecureServiceServer) SecureEcho(context.Context, *SecureEnvelope) (*SecureEnvelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureEcho not implemented")
}
func (UnimplementedSecureServiceServer) SecureBidiEcho(grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method SecureBidiEcho not implemented")
}
func (UnimplementedSecureServiceServer) UnorderedBidiEcho(grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method UnorderedBidiEcho not implemented")
}
func (UnimplementedSecureServiceServer) InspectOuter(context.Context, *SecureEnvelope) (*SecureEnvelope, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectOuter not implemented")
}
func (UnimplementedSecureServiceServer) mustEmbedUnimplementedSecureServiceServer() {}
func (UnimplementedSecureServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureServiceServer will
// result in compilation errors.
type UnsafeSecureServiceServer interface {
	mustEmbedUnimplementedSecureServiceServer()
}

func RegisterSecureServiceServer(s grpc.ServiceRegistrar, srv SecureServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecureService_ServiceDesc, srv)
}

func _SecureService_SecureEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureServiceServer).SecureEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureService_SecureEcho_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureServiceServer).SecureEcho(ctx, req.(*SecureEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureService_SecureBidiEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecureServiceServer).SecureBidiEcho(&grpc.GenericServerStream[SecureEnvelope, SecureEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecureService_SecureBidiEchoServer = grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]

func _SecureService_UnorderedBidiEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SecureServiceServer).UnorderedBidiEcho(&grpc.GenericServerStream[SecureEnvelope, SecureEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecureService_UnorderedBidiEchoServer = grpc.BidiStreamingServer[SecureEnvelope, SecureEnvelope]

func _SecureService_InspectOuter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureServiceServer).InspectOuter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureService_InspectOuter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureServiceServer).InspectOuter(ctx, req.(*SecureEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

// SecureService_ServiceDesc is the grpc.ServiceDesc for SecureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.SecureService",
	HandlerType: (*SecureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SecureEcho",
			Handler:    _SecureService_SecureEcho_Handler,
		},
		{
			MethodName: "InspectOuter",
			Handler:    _SecureService_InspectOuter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SecureBidiEcho",
			Handler:       _SecureService_SecureBidiEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnorderedBidiEcho",
			Handler:       _SecureService_UnorderedBidiEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/echo/echo.proto",
}
